[package]
name = "basic-project-template"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { version = "1.2.0", features = ["esp32c3", "unstable"] }
esp-backtrace = { version = "0.20.0", features = ["esp32c3", "println"]}
esp-println = { version = "0.18.0", features = ["esp32c3"]}
critical-section = { version = "1.2.0"}
libm = { version = "0.2.16"}
log = "0.4.22"
